### PR TITLE
feat: Bump to Hugo 0.121.1 [release]

### PR DESCRIPTION
**Pull request by mbevc1**
Use latest upstream

### CODE REVIEW

**Review by FelicianoTech — APPROVED** [review]

**Comment by FelicianoTech** [comment]
For since reason it didn't publish. I'm on the road right now but I'll look into this tonight.

**Comment by mbevc1** [comment]
Okay, thanks! Let me know if there is something I've should have done differently in the PR

**Comment by FelicianoTech** [comment]
Fixed.

Your PR had a small issues. For a Docker image/tag release, the commit message needs to have the string `[release]` in it.

I did catch this issue and added it in the title of the PR but it didn't change the commit message as I thought.

**Comment by mbevc1** [comment]
Gotcha, thanks

**Pull request merged**
