### PR TITLE
feat: Bump to 0.111.3

### LINKED ISSUE #300: Release v0.111.3
Upstream has released v.0.111.3: https://github.com/gohugoio/hugo/releases/tag/v0.111.3

### PR DESCRIPTION
**Pull request by mbevc1**
Closes #300

### CODE REVIEW

**Review by FelicianoTech — APPROVED** [review]
Thank you.

**Comment by mbevc1** [comment]
When is going to be published to Docker Hub?

**Comment by FelicianoTech** [comment]
In a few minutes. I had to make a new PR (https://github.com/hubci/hugo-docker/pull/302).

Your PR was good but didn't include the string `[release]` in the commit message. I missed it in my review.

**Comment by mbevc1** [comment]
Ahh, sorry about that - wan't sure what is triggering the pipelines :)

**Pull request merged**
